// Robotikaren Lantegiaren glosarioa
// [euskara, gaztelania, ingelesa, definizioa, unitatea]
export const HITZAK = [
  // ---------- pentsamendu konputazionala ----------
  ['abstrakzioa', 'abstracción', 'abstraction', 'Garrantzitsua dena gorde eta beharrezkoak ez diren xehetasunak alde batera uztea.', 'pentsamendu-konputazionala'],
  ['algoritmoa', 'algoritmo', 'algorithm', 'Problema bat ebazteko urrats ordenatu, zehatz eta finituen zerrenda.', 'pentsamendu-konputazionala'],
  ['bilaketa bitarra', 'búsqueda binaria', 'binary search', 'Datu ordenatuetan, urrats bakoitzean aukeren erdia baztertuz bilatzea.', 'pentsamendu-konputazionala'],
  ['deskonposizioa', 'descomposición', 'decomposition', 'Problema handi bat zati txikiago eta errazagoetan banatzea.', 'pentsamendu-konputazionala'],
  ['konplexutasuna', 'complejidad', 'complexity', 'Datuen tamaina handitzean algoritmo batek behar dituen urratsak nola hazten diren: O(n), O(log n)…', 'pentsamendu-konputazionala'],
  ['patroia', 'patrón', 'pattern', 'Problema bateko zatien arteko antzekotasuna, irtenbide bera berrerabiltzeko.', 'pentsamendu-konputazionala'],
  ['pentsamendu konputazionala', 'pensamiento computacional', 'computational thinking', 'Problemak ordenagailu batek edo pertsona batek jarraitu ahal izateko moduan ebazteko pentsatzeko modua.', 'pentsamendu-konputazionala'],
  ['programa', 'programa', 'program', 'Ordenagailu batek ulertzen duen lengoaian idatzitako algoritmoa.', 'pentsamendu-konputazionala'],

  // ---------- algoritmoak ----------
  ['begizta', 'bucle', 'loop', 'Urrats-multzo bat hainbat aldiz errepikatzen duen egitura.', 'algoritmoak'],
  ['erabakia', 'decisión', 'decision', 'Baldintza baten arabera bide bat edo beste hartzen duen urratsa; erronboa fluxu-diagraman.', 'algoritmoak'],
  ['fluxu-diagrama', 'diagrama de flujo', 'flowchart', 'Algoritmo baten urratsak ikur normalizatuekin eta geziekin irudikatzea.', 'algoritmoak'],
  ['irteera', 'salida', 'output', 'Algoritmoak edo programak ematen dituen emaitzak.', 'algoritmoak'],
  ['iterazioa', 'iteración', 'iteration', 'Begizta baten itzuli bakoitza.', 'algoritmoak'],
  ['sarrera', 'entrada', 'input', 'Algoritmoak edo programak kanpotik jasotzen dituen datuak.', 'algoritmoak'],
  ['sekuentzia', 'secuencia', 'sequence', 'Aginduak bata bestearen atzetik, ordenan, exekutatzea.', 'algoritmoak'],
  ['trazatzea', 'traza, seguimiento', 'trace', 'Algoritmo bat eskuz urratsez urrats exekutatzea, aldagaien balioak idatziz.', 'algoritmoak'],

  // ---------- blokeak ----------
  ['baldintza', 'condición', 'condition', 'Egia edo gezurra izan daitekeen adierazpena; erabakietan eta begiztetan erabiltzen da.', 'blokeak'],
  ['begizta habiaratua', 'bucle anidado', 'nested loop', 'Beste begizta baten barruan dagoen begizta.', 'blokeak'],
  ['blokea', 'bloque', 'block', 'Puzzle-pieza itxurako agindua bloke bidezko programazioan.', 'blokeak'],
  ['errepikapena', 'repetición', 'repetition', 'Bloke-multzo bat zenbaki jakin bat aldiz edo baldintza bat bete arte exekutatzea.', 'blokeak'],
  ['gertaera', 'evento', 'event', 'Programaren zati bat abiarazten duen gertakaria: programa hastea, botoi bat sakatzea…', 'blokeak'],

  // ---------- aldagaiak ----------
  ['aldagaia', 'variable', 'variable', 'Izen bat duen memoria-lekua, balio bat gordetzen duena eta alda daitekeena.', 'aldagaiak'],
  ['boolearra', 'booleano', 'Boolean', 'Bi balio bakarrik izan ditzakeen datua: egia edo gezurra.', 'aldagaiak'],
  ['datu mota', 'tipo de dato', 'data type', 'Aldagai batek gorde dezakeen balio mota: zenbakia, testua, boolearra…', 'aldagaiak'],
  ['eragilea', 'operador', 'operator', 'Balioekin eragiketa bat egiten duen ikurra: +, −, ×, ÷, mod, <, =…', 'aldagaiak'],
  ['esleipena', 'asignación', 'assignment', 'Aldagai batean balio bat gordetzea (x ← 5).', 'aldagaiak'],
  ['hondarra (mod)', 'resto (módulo)', 'remainder (modulo)', 'Zatiketa oso baten hondarra: 7 mod 3 = 1.', 'aldagaiak'],
  ['kontagailua', 'contador', 'counter', 'Gertaera bakoitzean bat gehitzen zaion aldagaia.', 'aldagaiak'],
  ['metagailua', 'acumulador', 'accumulator', 'Balioak batzen (edo biderkatzen) dituen aldagaia.', 'aldagaiak'],
  ['testu-katea', 'cadena de texto', 'string', 'Karaktere-segida bat, komatxo artean idazten dena.', 'aldagaiak'],

  // ---------- arazketa ----------
  ['akats logikoa', 'error lógico', 'logic error', 'Programa errorerik gabe amaitzen da, baina emaitza okerra da.', 'arazketa'],
  ['arazketa', 'depuración', 'debugging', 'Programa bateko akatsak aurkitu, ulertu eta zuzentzea.', 'arazketa'],
  ['begizta amaigabea', 'bucle infinito', 'infinite loop', 'Inoiz amaitzen ez den begizta, baldintza beti betetzen delako.', 'arazketa'],
  ['eten-puntua', 'punto de interrupción', 'breakpoint', 'Programa lerro jakin batean gelditzeko marka, egoera aztertzeko.', 'arazketa'],
  ['exekuzio-akatsa', 'error de ejecución', 'runtime error', 'Programa exekutatzen ari dela gertatzen den akatsa, adibidez zeroz zatitzea.', 'arazketa'],
  ['proba-kasua', 'caso de prueba', 'test case', 'Programa probatzeko datu-multzoa, espero den emaitzarekin.', 'arazketa'],
  ['sintaxi-akatsa', 'error de sintaxis', 'syntax error', 'Lengoaiaren idazteko arauak betetzen ez dituen akatsa.', 'arazketa'],

  // ---------- Micro:bit ----------
  ['azelerometroa', 'acelerómetro', 'accelerometer', 'Azelerazioa, astinduak eta inklinazioa neurtzen dituen sentsorea.', 'microbit'],
  ['LED pantaila', 'matriz de LED', 'LED matrix', 'LEDez osatutako sareta, irudiak eta testuak erakusteko.', 'microbit'],
  ['mikrokontrolagailua', 'microcontrolador', 'microcontroller', 'Prozesadorea, memoria eta sarrera-irteerak txip bakarrean dituen ordenagailu txikia.', 'microbit'],
  ['pina', 'pin', 'pin', 'Plaka batek zirkuitu bat konektatzeko duen kontaktua.', 'microbit'],
  ['seinale analogikoa', 'señal analógica', 'analog signal', 'Tarte bateko edozein balio har dezakeen seinalea.', 'microbit'],
  ['seinale digitala', 'señal digital', 'digital signal', 'Bi balio bakarrik dituen seinalea: 0 edo 1.', 'microbit'],

  // ---------- sentsoreak eta eragingailuak ----------
  ['ADC (bihurgailu analogiko-digitala)', 'convertidor analógico-digital (ADC)', 'analog-to-digital converter (ADC)', 'Tentsio analogikoa zenbaki bihurtzen duen zirkuitua; Arduino UNOn 10 bitekoa (0–1023).', 'sentsoreak-eragingailuak'],
  ['eragingailua', 'actuador', 'actuator', 'Seinale elektriko bat ekintza fisiko bihurtzen duen gailua: motorra, LEDa, buzzerra…', 'sentsoreak-eragingailuak'],
  ['H zubia', 'puente en H', 'H-bridge', 'DC motor baten biraketa-noranzkoa aldatzeko lau etengailuko zirkuitua.', 'sentsoreak-eragingailuak'],
  ['lan-zikloa', 'ciclo de trabajo', 'duty cycle', 'PWM seinale bat piztuta dagoen denbora-zatia, ehunekotan.', 'sentsoreak-eragingailuak'],
  ['PIR sentsorea', 'sensor PIR', 'PIR sensor', 'Pertsonen mugimendua infragorri-erradiazioaren aldaketaz detektatzen duen sentsorea.', 'sentsoreak-eragingailuak'],
  ['pull-down erresistentzia', 'resistencia pull-down', 'pull-down resistor', 'Sarrera bat 0 V-ra eramaten duen erresistentzia, ezer konektatuta ez dagoenean.', 'sentsoreak-eragingailuak'],
  ['PWM', 'modulación por ancho de pulso (PWM)', 'pulse-width modulation (PWM)', 'Seinale digital bat azkar piztu eta itzaliz batez besteko potentzia erregulatzea.', 'sentsoreak-eragingailuak'],
  ['sentsorea', 'sensor', 'sensor', 'Magnitude fisiko bat seinale elektriko bihurtzen duen gailua.', 'sentsoreak-eragingailuak'],
  ['servomotorra', 'servomotor', 'servo motor', 'Angelu zehatz batera biratzen den motorra, pultsuaren iraupenaz kontrolatua.', 'sentsoreak-eragingailuak'],
  ['ultrasoinu-sentsorea', 'sensor de ultrasonidos', 'ultrasonic sensor', 'Soinu-pultsu baten oihartzunaren denborarekin distantzia neurtzen duen sentsorea.', 'sentsoreak-eragingailuak'],
  ['urrats-motorra', 'motor paso a paso', 'stepper motor', 'Urrats zehatzetan biratzen den motorra.', 'sentsoreak-eragingailuak'],

  // ---------- kontrol-sistemak ----------
  ['atzeraelikadura', 'realimentación', 'feedback', 'Irteeraren informazioa sarrerara itzultzea, kontrolagailuak zuzen dezan.', 'kontrol-sistemak'],
  ['begizta irekia', 'lazo abierto', 'open loop', 'Irteera neurtzen ez duen kontrol-sistema.', 'kontrol-sistemak'],
  ['begizta itxia', 'lazo cerrado', 'closed loop', 'Irteera neurtu eta konsignarekin konparatzen duen kontrol-sistema.', 'kontrol-sistemak'],
  ['errorea (kontrolean)', 'error', 'error', 'Konsignaren eta neurtutako balioaren arteko diferentzia.', 'kontrol-sistemak'],
  ['histeresia', 'histéresis', 'hysteresis', 'Pizteko eta itzaltzeko atalase desberdinak erabiltzea, etengabeko aldaketak saihesteko.', 'kontrol-sistemak'],
  ['konsigna', 'consigna', 'setpoint', 'Kontrol-sistemak lortu behar duen balioa.', 'kontrol-sistemak'],
  ['kontrol-sistema', 'sistema de control', 'control system', 'Magnitude bat nahi den balioan mantentzeko elementuen multzoa.', 'kontrol-sistemak'],
  ['kontrolagailu proportzionala', 'controlador proporcional', 'proportional controller', 'Errorearekiko proportzionala den ekintza ematen duen kontrolagailua: u = Kp · e.', 'kontrol-sistemak'],
  ['perturbazioa', 'perturbación', 'disturbance', 'Kontrol-sistemaren irteera aldatzen duen kanpoko aldaketa.', 'kontrol-sistemak'],
  ['PID kontrolagailua', 'controlador PID', 'PID controller', 'Ekintza proportzionala, integrala eta deribatiboa konbinatzen dituen kontrolagailua.', 'kontrol-sistemak'],
  ['termostatoa', 'termostato', 'thermostat', 'Tenperatura kontrolatzeko gailua.', 'kontrol-sistemak'],

  // ---------- Arduino ----------
  ['Arduino', 'Arduino', 'Arduino', 'Hardware libreko mikrokontrolagailu-plaka, prototipoak eta hezkuntzarako proiektuak egiteko.', 'arduino'],
  ['hardware librea', 'hardware libre', 'open hardware', 'Diseinua publikoa den eta edonork alda eta fabrika dezakeen hardwarea.', 'arduino'],
  ['liburutegia', 'biblioteca, librería', 'library', 'Beste batzuek idatzitako funtzio-multzoa, programetan erabiltzeko.', 'arduino'],
  ['loop()', 'loop()', 'loop()', 'Arduino programan etengabe errepikatzen den funtzioa.', 'arduino'],
  ['protoboarda', 'placa de prototipos (protoboard)', 'breadboard', 'Soldatu gabe zirkuituak muntatzeko zulodun plaka.', 'arduino'],
  ['serie-monitorea', 'monitor serie', 'serial monitor', 'Plakak USB bidez bidalitako testuak ordenagailuan ikusteko leihoa.', 'arduino'],
  ['setup()', 'setup()', 'setup()', 'Arduino programan plaka piztean behin exekutatzen den funtzioa.', 'arduino'],

  // ---------- aplikazio mugikorrak ----------
  ['aldagai globala', 'variable global', 'global variable', 'Programa osoan, gertaera guztietan, erabil daitekeen aldagaia.', 'aplikazioak'],
  ['aplikazio mugikorra', 'aplicación móvil', 'mobile app', 'Telefono edo tableta batean exekutatzen den programa.', 'aplikazioak'],
  ['baimena', 'permiso', 'permission', 'Aplikazio batek kamera, kokapena edo beste datu batzuk erabiltzeko eskatzen duen onarpena.', 'aplikazioak'],
  ['gertaeretan oinarritutako programazioa', 'programación orientada a eventos', 'event-driven programming', 'Programak erabiltzailearen edo sistemaren gertaerei erantzuten die, eta bitartean zain dago.', 'aplikazioak'],
  ['interfazea', 'interfaz de usuario', 'user interface', 'Erabiltzaileak aplikazioarekin elkarreragiteko pantaila eta kontrolak.', 'aplikazioak'],
  ['irisgarritasuna', 'accesibilidad', 'accessibility', 'Pertsona guztiek, ezgaitasunak dituztenek barne, erabili ahal izatea.', 'aplikazioak'],
  ['osagaia (aplikazioa)', 'componente', 'component', 'Aplikazio baten pieza: botoia, etiketa, irudia, tenporizadorea…', 'aplikazioak'],
  ['tenporizadorea', 'temporizador', 'timer', 'Denbora-tarte jakin bat igarotzean gertaera bat sortzen duen osagaia.', 'aplikazioak'],

  // ---------- testu bidezko programazioa ----------
  ['C++', 'C++', 'C++', 'Lengoaia konpilatu azkarra; Arduino programatzeko erabiltzen da.', 'testu-programazioa'],
  ['funtzioa', 'función', 'function', 'Izena duen agindu-multzoa, parametroekin deitu eta berrerabil daitekeena.', 'testu-programazioa'],
  ['gainezkatzea', 'desbordamiento', 'overflow', 'Balio batek bere datu motaren tartea gainditzea.', 'testu-programazioa'],
  ['interpretatzailea', 'intérprete', 'interpreter', 'Programa lerroz lerro irakurri eta exekutatzen duen programa.', 'testu-programazioa'],
  ['konpilatzailea', 'compilador', 'compiler', 'Programa osoa makina-kode bihurtzen duen programa.', 'testu-programazioa'],
  ['koska', 'sangría', 'indentation', 'Lerro baten hasierako zuriuneak; Python-en blokeak zehazten ditu.', 'testu-programazioa'],
  ['Python', 'Python', 'Python', 'Lengoaia interpretatu erraz eta oso erabilia; blokeak koskarekin adierazten ditu.', 'testu-programazioa'],
  ['sintaxia', 'sintaxis', 'syntax', 'Programazio-lengoaia baten idazteko arauak.', 'testu-programazioa'],

  // ---------- osagai elektronikoak ----------
  ['anodoa', 'ánodo', 'anode', 'Diodo baten mutur positiboa; korrontea bertatik sartzen da.', 'osagai-elektronikoak'],
  ['asetasuna', 'saturación', 'saturation', 'Transistoreak kargak ahal duen korronte guztia uzten duen egoera: etengailu itxia.', 'osagai-elektronikoak'],
  ['denbora-konstantea (τ)', 'constante de tiempo (τ)', 'time constant (τ)', 'τ = R · C: kondentsadore bat % 63 kargatzeko behar den denbora.', 'osagai-elektronikoak'],
  ['diodoa', 'diodo', 'diode', 'Korrontea noranzko bakarrean uzten duen osagai erdieroalea.', 'osagai-elektronikoak'],
  ['ebakidura', 'corte', 'cut-off', 'Transistoreak korronterik uzten ez duen egoera: etengailu irekia.', 'osagai-elektronikoak'],
  ['erdieroalea', 'semiconductor', 'semiconductor', 'Eroale eta isolatzaileen arteko materiala (silizioa); diodoak eta transistoreak egiteko.', 'osagai-elektronikoak'],
  ['errelea', 'relé', 'relay', 'Elektroiman batek kontaktu bat ixten duen etengailu elektromagnetikoa.', 'osagai-elektronikoak'],
  ['igorlea', 'emisor', 'emitter', 'NPN transistore batean korronte guztia irteten den terminala.', 'osagai-elektronikoak'],
  ['kapazitatea', 'capacidad', 'capacitance', 'Kondentsadore batek tentsio-unitate bakoitzeko metatzen duen karga; faradetan (F) neurtzen da.', 'osagai-elektronikoak'],
  ['katodoa', 'cátodo', 'cathode', 'Diodo baten mutur negatiboa; LEDean hanka motza.', 'osagai-elektronikoak'],
  ['kolektorea', 'colector', 'collector', 'NPN transistore batean kargaren korrontea sartzen den terminala.', 'osagai-elektronikoak'],
  ['kondentsadorea', 'condensador', 'capacitor', 'Karga elektrikoa metatu eta askatzen duen osagaia.', 'osagai-elektronikoak'],
  ['LDR', 'fotorresistencia (LDR)', 'photoresistor (LDR)', 'Argiarekin erresistentzia jaisten zaion osagaia.', 'osagai-elektronikoak'],
  ['LEDa', 'LED', 'LED', 'Argia igortzen duen diodoa.', 'osagai-elektronikoak'],
  ['NTC termistorea', 'termistor NTC', 'NTC thermistor', 'Tenperaturarekin erresistentzia jaisten zaion osagaia.', 'osagai-elektronikoak'],
  ['oinarria (transistorea)', 'base', 'base', 'Kontrol-korrontea sartzen den transistorearen terminala.', 'osagai-elektronikoak'],
  ['potentziometroa', 'potenciómetro', 'potentiometer', 'Kurtsore mugikorra duen erresistentzia aldakorra.', 'osagai-elektronikoak'],
  ['transistorea', 'transistor', 'transistor', 'Korronte txiki batekin korronte handi bat kontrolatzen duen osagai erdieroalea.', 'osagai-elektronikoak'],

  // ---------- sistema bitarra ----------
  ['ASCII', 'ASCII', 'ASCII', 'Karaktere bakoitzari zenbaki bat esleitzen dion kodea: «A» = 65.', 'bitarra'],
  ['bita', 'bit', 'bit', 'Informazio-unitaterik txikiena: 0 edo 1.', 'bitarra'],
  ['bytea', 'byte', 'byte', '8 biteko multzoa.', 'bitarra'],
  ['kilobytea (KB)', 'kilobyte (KB)', 'kilobyte (KB)', '1024 byte.', 'bitarra'],
  ['osagarri bikoa', 'complemento a dos', "two's complement", 'Zenbaki negatiboak bitarrez adierazteko metodoa.', 'bitarra'],
  ['posizio-pisua', 'peso posicional', 'place value', 'Digitu baten balioa bere posizioaren arabera: bitarrean 1, 2, 4, 8…', 'bitarra'],
  ['sistema bitarra', 'sistema binario', 'binary system', '2 oinarriko zenbaki-sistema, 0 eta 1 digituekin.', 'bitarra'],
  ['sistema hamaseitarra', 'sistema hexadecimal', 'hexadecimal system', '16 oinarriko zenbaki-sistema: 0–9 eta A–F.', 'bitarra'],

  // ---------- ate logikoak ----------
  ['ate logikoa', 'puerta lógica', 'logic gate', 'Eragiketa logiko bat egiten duen zirkuitu elektronikoa.', 'ate-logikoak'],
  ['Boole-ren aljebra', 'álgebra de Boole', 'Boolean algebra', '0 eta 1 balioekin eta EZ, ETA eta EDO eragiketekin lan egiten duen aljebra.', 'ate-logikoak'],
  ['De Morgan-en legeak', 'leyes de De Morgan', "De Morgan's laws", 'ETA baten ezeztapena ezeztapenen EDO bat da, eta EDO batena ezeztapenen ETA bat.', 'ate-logikoak'],
  ['EDO atea', 'puerta OR', 'OR gate', 'Sarreraren bat 1 denean 1 ematen duen atea.', 'ate-logikoak'],
  ['EDO-B atea', 'puerta XOR', 'XOR gate', 'Sarrerak desberdinak direnean 1 ematen duen atea (EDO esklusiboa).', 'ate-logikoak'],
  ['egia-taula', 'tabla de verdad', 'truth table', 'Sarreren konbinazio guztiak eta bakoitzaren irteera erakusten dituen taula.', 'ate-logikoak'],
  ['ETA atea', 'puerta AND', 'AND gate', 'Sarrera guztiak 1 direnean bakarrik 1 ematen duen atea.', 'ate-logikoak'],
  ['EZ atea', 'puerta NOT', 'NOT gate', 'Sarreraren aurkako balioa ematen duen atea.', 'ate-logikoak'],
  ['EZ-EDO atea', 'puerta NOR', 'NOR gate', 'EDO baten aurkakoa; ate unibertsala.', 'ate-logikoak'],
  ['EZ-ETA atea', 'puerta NAND', 'NAND gate', 'ETA baten aurkakoa; ate unibertsala.', 'ate-logikoak'],

  // ---------- diseinu logikoa ----------
  ['berdin dio (X)', 'indiferente (X)', "don't care (X)", 'Inoiz gertatzen ez den konbinazioa; 0 edo 1 bezala har daiteke sinplifikatzeko.', 'logika-diseinua'],
  ['biegonkorra', 'biestable', 'flip-flop', 'Bit bat gordetzen duen zirkuitua, bi egoera egonkorrekin.', 'logika-diseinua'],
  ['erloju-seinalea', 'señal de reloj', 'clock signal', 'Zirkuitu sekuentzialak sinkronizatzen dituen pultsu-seinale erregularra.', 'logika-diseinua'],
  ['forma kanonikoa', 'forma canónica', 'canonical form', 'Minterminoen EDO bat: produktuen batura.', 'logika-diseinua'],
  ['Gray kodea', 'código Gray', 'Gray code', 'Ondoz ondoko balioak bit bakar batean desberdintzen diren kodea.', 'logika-diseinua'],
  ['Karnaugh-en mapa', 'mapa de Karnaugh', 'Karnaugh map', 'Egia-taula Gray kodean antolatuta, adierazpen logikoak sinplifikatzeko.', 'logika-diseinua'],
  ['minterminoa', 'minitérmino', 'minterm', 'Aldagai guztien ETA bat, irteera 1 duen errenkada bati dagokiona.', 'logika-diseinua'],
  ['zirkuitu konbinazionala', 'circuito combinacional', 'combinational circuit', 'Irteera uneko sarreren araberakoa bakarrik den zirkuitua.', 'logika-diseinua'],
  ['zirkuitu sekuentziala', 'circuito secuencial', 'sequential circuit', 'Irteera aurreko egoeraren araberakoa ere bada: memoria du.', 'logika-diseinua'],

  // ---------- pneumatika ----------
  ['3/2 balbula', 'válvula 3/2', '3/2 valve', '3 bide (portu) eta 2 posizio dituen balbula.', 'pneumatika'],
  ['5/2 balbula', 'válvula 5/2', '5/2 valve', '5 bide eta 2 posizio dituen balbula; efektu bikoitzeko zilindroetarako.', 'pneumatika'],
  ['balbula', 'válvula', 'valve', 'Airearen bidea ireki, itxi edo aldatzen duen osagaia.', 'pneumatika'],
  ['bar', 'bar', 'bar', 'Presio-unitatea: 1 bar = 100 000 Pa = 0,1 N/mm² ≈ 1 atm.', 'pneumatika'],
  ['efektu bakuneko zilindroa', 'cilindro de simple efecto', 'single-acting cylinder', 'Aireak noranzko batean bultzatzen du, eta malgukiak itzultzen du.', 'pneumatika'],
  ['efektu bikoitzeko zilindroa', 'cilindro de doble efecto', 'double-acting cylinder', 'Aireak bi noranzkoetan bultzatzen du.', 'pneumatika'],
  ['emari-erregulagailua', 'regulador de caudal', 'flow control valve', 'Airearen emaria murrizten duen balbula, zilindroaren abiadura kontrolatzeko.', 'pneumatika'],
  ['enboloa', 'émbolo, pistón', 'piston', 'Zilindroaren barruan mugitzen den pieza, aireak bultzatua.', 'pneumatika'],
  ['hidraulika', 'hidráulica', 'hydraulics', 'Olioa bezalako likidoak energia transmititzeko erabiltzen dituen teknologia.', 'pneumatika'],
  ['konpresorea', 'compresor', 'compressor', 'Airea hartu eta presioa igotzen dion makina.', 'pneumatika'],
  ['manometroa', 'manómetro', 'pressure gauge', 'Presioa neurtzeko tresna.', 'pneumatika'],
  ['pneumatika', 'neumática', 'pneumatics', 'Aire konprimitua energia gisa erabiltzen duen teknologia.', 'pneumatika'],
  ['unitate prestatzailea', 'unidad de mantenimiento', 'air service unit (FRL)', 'Airea iragazi, presioa erregulatu eta lubrifikatzen duen multzoa.', 'pneumatika'],
  ['zilindroa', 'cilindro', 'cylinder', 'Aire konprimituarekin mugimendu lineala sortzen duen eragingailua.', 'pneumatika'],
  ['zurtoina', 'vástago', 'piston rod', 'Enboloari lotuta zilindrotik ateratzen den barra.', 'pneumatika'],

  // ---------- zirkuitu pneumatikoak ----------
  ['aginte zeharkakoa', 'mando indirecto', 'indirect control', 'Balbula txiki batek aire-seinale batez balbula handi bat pilotatzen du.', 'pneumatika-zirkuituak'],
  ['aginte zuzena', 'mando directo', 'direct control', 'Operadoreak eragindako balbulak zilindroa zuzenean elikatzen du.', 'pneumatika-zirkuituak'],
  ['balbula biegonkorra', 'válvula biestable', 'bistable valve', 'Seinalea kendu arren azken posizioan geratzen den balbula: memoria.', 'pneumatika-zirkuituak'],
  ['bi presioko balbula', 'válvula de simultaneidad', 'two-pressure valve', 'ETA funtzioa: bi sarrerek presioa dutenean bakarrik du airea irteerak.', 'pneumatika-zirkuituak'],
  ['espazio-fase diagrama', 'diagrama espacio-fase', 'displacement-step diagram', 'Zilindro bakoitzaren posizioa urrats bakoitzean erakusten duen diagrama.', 'pneumatika-zirkuituak'],
  ['hautagailu-balbula', 'válvula selectora', 'shuttle valve', 'EDO funtzioa: bi sarreretako edozeinek elikatzen du irteera.', 'pneumatika-zirkuituak'],
  ['ibilbide-amaierako detektagailua', 'final de carrera', 'limit switch', 'Zilindro bat ibilbidearen muturrera iritsi dela adierazten duen balbula edo sentsorea.', 'pneumatika-zirkuituak'],
  ['kaskada-metodoa', 'método cascada', 'cascade method', 'Seinale-gatazkak saihesteko sekuentzia taldetan banatzen duen metodoa.', 'pneumatika-zirkuituak'],
  ['pilotaje pneumatikoa', 'pilotaje neumático', 'pneumatic pilot', 'Balbula bat aire-seinale batez eragitea.', 'pneumatika-zirkuituak'],
  ['PLCa', 'autómata programable (PLC)', 'programmable logic controller (PLC)', 'Industrian makinak kontrolatzeko ordenagailu sendoa.', 'pneumatika-zirkuituak'],
  ['seinale-gatazka', 'señal permanente, bloqueo', 'signal conflict', 'Balbula biegonkor baten bi pilotuek aldi berean presioa dutenean gertatzen den blokeoa.', 'pneumatika-zirkuituak'],

  // ---------- robotak ----------
  ['dronea', 'dron', 'drone', 'Pilotu gabeko aireko ibilgailua.', 'robotak'],
  ['enkoderra', 'encoder', 'encoder', 'Ardatz baten biraketa neurtzen duen sentsorea.', 'robotak'],
  ['erreduktorea', 'reductora', 'gearbox', 'Motorraren abiadura txikitu eta indarra handitzen duen engranaje-multzoa.', 'robotak'],
  ['infragorri-sentsorea', 'sensor de infrarrojos', 'infrared sensor', 'Argi infragorriaren islapena neurtuz gainazal zuriak eta beltzak bereizten dituen sentsorea.', 'robotak'],
  ['lerro-jarraitzailea', 'siguelíneas', 'line follower', 'Lurreko lerro bati sentsoreekin jarraitzen dion robota.', 'robotak'],
  ['odometria', 'odometría', 'odometry', 'Gurpilen birak neurtuz robotaren posizioa kalkulatzea.', 'robotak'],
  ['robot kolaboratiboa', 'robot colaborativo (cobot)', 'collaborative robot (cobot)', 'Pertsonen ondoan seguru lan egiteko diseinatutako robota.', 'robotak'],
  ['robota', 'robot', 'robot', 'Ingurunea hauteman, erabakiak hartu eta ekiten duen makina programagarria.', 'robotak'],
  ['trakzio diferentziala', 'tracción diferencial', 'differential drive', 'Bi gurpil independente dituen robota, abiadura desberdinekin biratzen dena.', 'robotak'],

  // ---------- robot-besoa ----------
  ['amaierako elementua', 'elemento terminal', 'end effector', 'Besoaren muturreko tresna: pintza, bentosa, soldagailua…', 'robot-besoa'],
  ['artikulazioa', 'articulación', 'joint', 'Bi segmenturen arteko lotura mugikorra, errotaziokoa edo prismatikoa.', 'robot-besoa'],
  ['askatasun-gradua', 'grado de libertad', 'degree of freedom', 'Modu independentean mugi daitekeen artikulazio bakoitza.', 'robot-besoa'],
  ['lan-eremua', 'espacio de trabajo', 'workspace', 'Robotaren muturra iris daitekeen puntuen multzoa.', 'robot-besoa'],
  ['manipulatzailea', 'manipulador', 'manipulator', 'Artikulazioz lotutako segmentuen katea, amaieran tresna bat duena.', 'robot-besoa'],
  ['pintza', 'pinza', 'gripper', 'Objektuak heltzeko amaierako elementua.', 'robot-besoa'],
  ['SCARA robota', 'robot SCARA', 'SCARA robot', 'Plano horizontalean biratzen diren bi artikulazio eta ardatz bertikal bat dituen robota.', 'robot-besoa'],
  ['zinematika alderantzizkoa', 'cinemática inversa', 'inverse kinematics', 'Amaierako elementuaren posiziotik artikulazioen angeluak kalkulatzea.', 'robot-besoa'],
  ['zinematika zuzena', 'cinemática directa', 'forward kinematics', 'Artikulazioen angeluetatik amaierako elementuaren posizioa kalkulatzea.', 'robot-besoa'],

  // ---------- gauzen Internet ----------
  ['aginte-panela', 'panel de control', 'dashboard', 'Datuak grafikoki erakusten dituen eta gailuak kontrolatzeko pantaila.', 'gauzen-internet'],
  ['Big Data', 'macrodatos (big data)', 'big data', 'Tresna arruntekin prozesatu ezin diren datu-multzo erraldoiak.', 'gauzen-internet'],
  ['ertzeko konputazioa', 'computación en el borde', 'edge computing', 'Datuak gailuan edo hurbil prozesatzea, dena hodeira bidali gabe.', 'gauzen-internet'],
  ['gaia (topic)', 'tema (topic)', 'topic', 'MQTT mezuak antolatzeko izen hierarkikoa: etxea/sukaldea/tenperatura.', 'gauzen-internet'],
  ['gauzen Internet (IoT)', 'internet de las cosas (IoT)', 'Internet of Things (IoT)', 'Internetera konektatutako objektu fisikoen sarea, sentsore eta eragingailuekin.', 'gauzen-internet'],
  ['hodeia', 'nube', 'cloud', 'Internet bidez erabiltzen diren urruneko zerbitzariak.', 'gauzen-internet'],
  ['JSON', 'JSON', 'JSON', 'Datuak testuz trukatzeko formatua, gako-balio bikoteekin.', 'gauzen-internet'],
  ['lo-modua', 'modo de bajo consumo', 'sleep mode', 'Gailu batek energia aurrezteko ia dena itzaltzen duen egoera.', 'gauzen-internet'],
  ['LoRaWAN', 'LoRaWAN', 'LoRaWAN', 'Irismen luzeko eta kontsumo txikiko haririk gabeko sarea.', 'gauzen-internet'],
  ['MQTT', 'MQTT', 'MQTT', 'Argitaratu-harpidetu ereduko mezularitza-protokolo arina.', 'gauzen-internet'],
  ['zerbitzaria (broker)', 'bróker', 'broker', 'MQTT-n mezuak jaso eta harpidedunei bidaltzen dizkien zerbitzaria.', 'gauzen-internet'],

  // ---------- adimen artifiziala ----------
  ['adimen artifiziala (AA)', 'inteligencia artificial (IA)', 'artificial intelligence (AI)', 'Gizakion adimena behar duten zereginak egiten dituzten sistema informatikoen arloa.', 'adimen-artifiziala'],
  ['alborapena', 'sesgo', 'bias', 'Datu desorekatuen ondorioz ereduak talde batzuekin akats gehiago egitea.', 'adimen-artifiziala'],
  ['entrenamendu-datuak', 'datos de entrenamiento', 'training data', 'Eredua ikasteko erabiltzen diren adibideak.', 'adimen-artifiziala'],
  ['eredua', 'modelo', 'model', 'Datuetatik ikasitako eta iragarpenak egiten dituen sistema.', 'adimen-artifiziala'],
  ['errefortzu bidezko ikasketa', 'aprendizaje por refuerzo', 'reinforcement learning', 'Sariak eta zigorrak jasoz, probatuz ikastea.', 'adimen-artifiziala'],
  ['gainegokitzea', 'sobreajuste', 'overfitting', 'Ereduak entrenamendu-datuak buruz ikastea eta datu berriekin huts egitea.', 'adimen-artifiziala'],
  ['ikasketa automatikoa', 'aprendizaje automático', 'machine learning', 'Sistemak datuetatik ikastea, arauak eskuz programatu gabe.', 'adimen-artifiziala'],
  ['ikasketa gainbegiratua', 'aprendizaje supervisado', 'supervised learning', 'Adibide etiketatuekin entrenatzea.', 'adimen-artifiziala'],
  ['ikasketa gainbegiratu gabea', 'aprendizaje no supervisado', 'unsupervised learning', 'Etiketarik gabeko datuetan antzeko taldeak aurkitzea.', 'adimen-artifiziala'],
  ['ikasketa sakona', 'aprendizaje profundo', 'deep learning', 'Geruza askoko sare neuronalekin ikastea.', 'adimen-artifiziala'],
  ['k-NN (k auzokide hurbilenak)', 'k vecinos más cercanos (k-NN)', 'k-nearest neighbours (k-NN)', 'Adibide berri bat k adibide antzekoenen gehiengoaren klasearekin sailkatzen duen algoritmoa.', 'adimen-artifiziala'],
  ['neurona artifiziala', 'neurona artificial', 'artificial neuron', 'Sarrerak pisuekin batu eta aktibazio-funtzio bat aplikatzen duen unitatea.', 'adimen-artifiziala'],
  ['pisua (neurona)', 'peso', 'weight', 'Neurona batean sarrera baten garrantzia adierazten duen zenbakia.', 'adimen-artifiziala'],
  ['proba-datuak', 'datos de prueba', 'test data', 'Eredua ebaluatzeko gordetako datuak, entrenamenduan erabili gabeak.', 'adimen-artifiziala'],
  ['sailkapena', 'clasificación', 'classification', 'Adibide bati kategoria bat esleitzea.', 'adimen-artifiziala'],
  ['sare neuronala', 'red neuronal', 'neural network', 'Geruzatan antolatutako neurona artifizialen multzoa.', 'adimen-artifiziala'],
  ['zehaztasuna', 'exactitud', 'accuracy', 'Asmatutako iragarpenen ehunekoa, guztien artean.', 'adimen-artifiziala']
];
